### PR TITLE
add date function from post.html

### PR DESCRIPTION
**Pull request by xaoseric**
Add the date function from https://github.com/mybb/mybb-com/blob/gh-pages/_layouts/post.html so we can display when page was created or updated.

### CODE REVIEW

**Comment by pkill37** [comment]
I would argue this information isn't useful. Can you elaborate why the docs needs a created/updated date?

It's also worth noting the post.html layout isn't used in the mybb/mybb.com repository as far as I can see. It's just sitting there by default.

**Comment by xaoseric** [comment]
The docs need a created/updated date so end users can see when the information was last updated, and that way contributors are able to find the information that needs updating more easily.

**Comment by nmalcolm** [comment]
I think a "Last Modified" line would be quite handy. I don't think we need to show when it was created (assuming that's separate).

**Comment by Kaeden** [comment]
I agree with a **Last Modified** line.

**Comment by pkill37** [comment]
Implementing this means having to specify a date for each page, each time you change something.

It's inconvenient.

**Comment by Kaeden** [comment]
To me it seems this was already added. (https://github.com/mybb/mybb.com/blob/gh-pages/_layouts/post.html)

**Comment by pkill37** [comment]
@Kaeden: That's in the mybb/mybb.com repository. @xaoseric wanted to add precisely that to the docs.

Regardless, as I have already said, implementing this requires changing the date every time you edit a file, which is pretty inconvenient. So this should stay closed.

**Pull request closed without merging**
