### PR TITLE
Update standards.md

### PR DESCRIPTION
**Pull request by tnadolecki**

### CODE REVIEW

**Comment by JoshHarmon** [comment]
Good catch! Sad that we blatantly ignored the requirement outlined above it. Thank you for your contribution!

**Comment by Destroy666x** [comment]
Actually, escaping everything that way is not required, it's even frowned upon if the value is a simple constant string/whatever (no need for escaping in most cases then) or a variable integer/float/whatever (`(type)` casting is better then). The description is misleading, especially that simple constant strings that don't require escaping are used as examples.

**Comment by tnadolecki** [comment]
Right, It did not make sense...
PS: I will be reading thru more as I'm just beginning to learn...
Thanks!
T.

2015-11-13 16:02 GMT+00:00 Przemek Pawlas notifications@github.com:

**Comment by JoshHarmon** [comment]
Fair point, @Destroy666x. Would you advise reverting this change?

**Comment by Destroy666x** [comment]
Yes, and changing the "required" text to something more like "when required", an example with user input (`$mybb->get_input('randominput')` or whatever) would be nice for that case.

**Comment by JoshHarmon** [comment]
Alright, I'll revert this and add this to my todo, or @tnadolecki can make the changes and update with an improved PR.

**Pull request merged**
