### PR TITLE
Update 404

### PR DESCRIPTION
**Pull request by ghost**
Why 2 search?

### CODE REVIEW

**Comment by ghost** [comment]
quick question why is there a folder called 1.6 didn't the support for that stop?
@euantorano @Devilshakerz

**Comment by euantorano** [comment]
Official support for 1.6 has ended, but we still maintain documentation for it (though we don't generally add new pages to said documentation).

**Comment by katosdev** [comment]
Why remove the MyBB search functionality sorry. @LiveChief ?
@euantorano

**Comment by ghost** [comment]
there are 2 searches one on the top and the bottom look at any major sites they only have one and a back button

**Comment by katosdev** [comment]
Ahh, my apologies @LiveChief - was slightly stumped there! Makes sense to me...
I'll leave this to the Developers to have a look through.

**Comment by LiveChief** [comment]
u dont have to say sorry over the internet lol, btw can u upload the files instead of having a zip on here
https://github.com/katosdev/MyTracker

**Comment by katosdev** [comment]
@LiveChief please keep this issue for MyBB related discussion, and open a separate issue on MyTracker for anything related to that. Though it has now been updated.

**Comment by JordanMussi** [comment]
If we are changing here then mybb/mybb.com needs to be changed as well.

Before we do though @justinsoltesz, do you have any comments? I think having the prominent search is good as it encourages the user to use it... Without it the user would hit back and carry on struggling to find what they're looking for.

**Comment by justinsoltesz** [comment]
I don't see why this needs to be changed. Providing a search box directly below the not found message is beneficial to users.

**Comment by JordanMussi** [comment]
Agreed. I think we will leave it there for now as it serves a purpose. Thanks for the suggestion though @LiveChief! :smiley:

**Pull request closed without merging**
