### PR TITLE
Implementing new website design

### PR DESCRIPTION
**Pull request by justinsoltesz**
Implements the new MyBB website design, referencing CSS resources from the mybb/mybb-com repository. A few other changes include modifying the name global URL variable, adding a global variable for the main site URL, and adding categories to most (if not all pages) so they can be cleanly organized on the index page (which is obviously a work in progress).

(My fork of the repository is accessible at http://jsoltesz.com/mybb.github.io)

### CODE REVIEW

**Comment by JordanMussi** [comment]
This looks great!
However, the version list tables don't generate correctly. I know it didn't work before, but it can't hurt fixing it. :wink:
Furthermore, there should be table of contents and anchors for the headings. I have looked into this and believe [this](https://github.com/ghiculescu/jekyll-table-of-contents) is the best short we have, as GitHub pages don't allow Jekyll plugins.

**Comment by justinsoltesz** [comment]
Those things weren't included in what I did...I think there are still plans to add/finish those things. I was simply setting up the new website wrapper.

**Comment by Kaeden** [comment]
Should we merge this or is it work in progress?

**Comment by JordanMussi** [comment]
It's finished, my comments earlier can be made in a new pull request.

**Comment by pkill37** [comment]
I had something different in mind, it involved a separate shared repository.

Ideally I wanted to share everything we could between the repositories, not just CSS. The includes and base layout in particular. We're kinda repeating ourselves here. But I'm still not sure how it can be done.

And realistically it wouldn't really solve an important problem. Sure, if we change a line of base HTML we're gonna have to do it twice, but how often is that going to happen after the site is rock solid? So this implementation works fine.

Unless someone has any idea on how to share **CSS, layouts and includes**, this can be merged.

**Comment by nmalcolm** [comment]
Yeah, I don't think we're going to get much better than this without over-complicating things. I don't see it being a major issue.

**Comment by JordanMussi** [comment]
How come the h2 tags on the index are visually larger than h1 tags?

**Comment by justinsoltesz** [comment]
The index is still very much a work in progress. There's probably some strange inherited CSS that's affecting those.

**Pull request merged**
