### PR TITLE
Add 1.8.4 release page

### PR DESCRIPTION
**Pull request by JoshHarmon**
Added version page for 1.8.4 as promised in #43

### CODE REVIEW

**Comment by JoshHarmon** [comment]
Question: Should install/ only list upgrade32?

**Comment by JoshHarmon** [comment]
As @Stefan-ST added the page himself, I'll close this :)

**Comment by Stefan-MyBB** [comment]
@JoshH99 Your PR also contains several mistakes like "There are **no** changes to **18** language files.". That's why I thought it is faster to add the page myself (which was planned anyway).

**Comment by JoshHarmon** [comment]
Ah I see. It's totally fine!

————$ whoami

josh

**Pull request closed without merging**
