### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by Ikerepc**
Tutorial for theme installation

### CODE REVIEW

**Comment by JoshHarmon** [comment]
Thank you for taking your time to contribute to the documentation. We appreciate the help, especially with building out the 1.8 Docs, which are looking somewhat scarce at the moment.

**Comment by Ikerepc** [comment]
Can you move it from administration to development/themes?
I just find that out, and I think that it would be right place for it... Sorry :)

**Comment by JoshHarmon** [comment]
Actually not sure I agree with that, because it's about installing (which falls under administration). If we put it in the development section, I'd expect to find a bunch of templating and styling resources for theme development.

**Comment by Ikerepc** [comment]
Oh, ok. Thanks.
That makes more sense :)

**Pull request merged**
