### PR TITLE
Adding Using FTP page, How to CHMOD page and Updating upgrade.md

### PR DESCRIPTION
**Pull request by Kaeden**
I'm adding Using FTP page, How to CHMOD and updating the upgrade page

### CODE REVIEW

**Comment by pkill37** [comment]
A few notes:
- Add a space after the heading symbols, e.g. `###Using FTP` should be `### Using FTP`
- Don't use more than one newline to separate blocks of text.
- When linking to internal pages use _relative_ links, e.g. `[Using FTP](http://docs.mybb.com/install/ftp)` should be `[Using FTP](ftp)` (the category in this case is not needed because the page we're writing this in is already inside `install/`).

Look at existing files if you're not sure what I mean. Anyway, this is not too important.

I'm actually debating myself whether the FTP and CHMOD pages should exist. Despite existing in the current docs, I don't think it's our responsibility to document how to use an FTP client or how to CHMOD files. The documentation is about **MyBB**. Whenever possible we should refer to these things by linking to more broad Wikipedia articles, tutorials made by the community or something like that.

The Upgrade page is fine though. In the future please make separate pull requests when making commits unrelated to the rest.

**Comment by Kaeden** [comment]
I think I corrected everything. I'm going to have to create multiple branches for separate commits.

**Comment by pkill37** [comment]
I should have made my second point more clear. **Don't use more than one newline, period.** Before and after headings there should only be one newline. Same thing for the YAML front matter (the layout and title stuff at the top), paragraphs, etc. Don't use _two_ newlines.

Can you move both `ftp.md` and `chmod.md` to `miscellaneous/`? It's general information, it's not specifically related to the installation. Also, please make the list of FTP clients a bullet point list.

Finally, and I'm just nitpicking here, try to write more meaningful commit messages. Explain what you did in the commit instead of just saying you updated some file. It looks nicer in the commit history. :)

**Comment by pkill37** [comment]
You also haven't yet updated `upgrade.md` with the notes I've made.

**Pull request closed without merging**
